use serde::{Deserialize, Serialize};

/// 武学静态定义（5门）
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MartialArt {
    pub id: String,
    pub name: String,
    #[serde(rename = "type")]
    pub art_type: String,
    pub desc: String,
    pub atk: i32,
    pub def: i32,
    pub spd: i32,
    #[serde(rename = "req_talent")]
    pub req_talent: i32,
    pub sect_id: Option<String>,
    pub basic_skill: String,
    pub difficulty: i32,
}

#[allow(clippy::too_many_arguments)]
fn art(
    id: &str,
    name: &str,
    art_type: &str,
    desc: &str,
    stats: (i32, i32, i32),
    req_talent: i32,
    sect_id: Option<&str>,
    basic_skill: &str,
) -> MartialArt {
    MartialArt {
        id: id.into(),
        name: name.into(),
        art_type: art_type.into(),
        desc: desc.into(),
        atk: stats.0,
        def: stats.1,
        spd: stats.2,
        req_talent,
        sect_id: sect_id.map(str::to_owned),
        basic_skill: basic_skill.into(),
        difficulty: (stats.0 + stats.1 + stats.2).max(5),
    }
}

/// 返回全部 5 门武学静态数据
pub fn all_martial_arts() -> Vec<MartialArt> {
    let mut arts = vec![
        art(
            "taixu",
            "太虚剑法",
            "剑法",
            "虚实相生，乃本派镇山绝学。",
            (3, 3, 2),
            30,
            Some("player"),
            "基本剑法",
        ),
        art(
            "jiuyang",
            "九阳烈掌",
            "掌法",
            "至刚至猛，掌风裂石。",
            (5, 1, 2),
            40,
            Some("player"),
            "基本拳脚",
        ),
        art(
            "xuanbing",
            "玄冰心经",
            "内功",
            "心如寒冰，以柔克刚。",
            (1, 5, 2),
            35,
            Some("player"),
            "基本内功",
        ),
        art(
            "zhuifeng",
            "追风步",
            "轻功",
            "踏雪无痕，追风逐电。",
            (2, 2, 5),
            25,
            Some("player"),
            "基本轻功",
        ),
        art(
            "hunyuan",
            "混元功",
            "内功",
            "根基浑厚，绵绵不绝。",
            (3, 3, 2),
            20,
            Some("player"),
            "基本内功",
        ),
        art(
            "taiji",
            "太极神功",
            "内功",
            "阴阳相济，以静制动。",
            (3, 6, 3),
            38,
            Some("wudang"),
            "基本内功",
        ),
        art(
            "dugu",
            "独孤九剑",
            "剑法",
            "料敌机先，无招胜有招。",
            (7, 2, 5),
            46,
            Some("huashan"),
            "基本剑法",
        ),
        art(
            "qiankun",
            "乾坤大挪移",
            "内功",
            "牵引挪移，化敌劲力。",
            (5, 5, 4),
            45,
            Some("mingjiao"),
            "基本内功",
        ),
        art(
            "xiantian",
            "先天功",
            "内功",
            "玄门正宗，返本归元。",
            (4, 6, 2),
            40,
            Some("quanzhen"),
            "基本内功",
        ),
        art(
            "liumai",
            "六脉神剑",
            "指法",
            "剑气纵横，隔空点穴。",
            (7, 2, 4),
            48,
            Some("tianlong"),
            "基本指法",
        ),
        art(
            "luoying",
            "落英神剑掌",
            "掌法",
            "落英缤纷，虚实莫测。",
            (5, 3, 5),
            42,
            Some("taohua"),
            "基本拳脚",
        ),
        art(
            "yijin",
            "易筋经",
            "内功",
            "洗髓易筋，禅武合一。",
            (4, 7, 2),
            44,
            Some("shaolin"),
            "基本内功",
        ),
        art(
            "yunu",
            "玉女心经",
            "内功",
            "清静无为，双剑合璧。",
            (3, 5, 5),
            40,
            Some("gumu"),
            "基本内功",
        ),
        art(
            "dagou",
            "打狗棒法",
            "棍法",
            "招式精奇，专制群邪。",
            (6, 4, 4),
            43,
            Some("gaibang"),
            "基本棍法",
        ),
        art(
            "jiuyin",
            "九阴真经",
            "内功",
            "阴柔深邃，包罗万象。",
            (5, 6, 4),
            46,
            Some("emei"),
            "基本内功",
        ),
        art(
            "kuihua",
            "葵花宝典",
            "内功",
            "身形如鬼魅，出手若电。",
            (6, 2, 8),
            50,
            Some("riyue"),
            "基本内功",
        ),
        art(
            "huagong",
            "化功大法",
            "内功",
            "以毒化劲，消人功力。",
            (6, 3, 3),
            38,
            Some("xingxiu"),
            "基本内功",
        ),
        art(
            "douzhuan",
            "斗转星移",
            "身法",
            "借力打力，彼道还施。",
            (5, 6, 5),
            47,
            Some("murong"),
            "基本轻功",
        ),
        art(
            "longxiang",
            "龙象般若功",
            "内功",
            "力大势沉，层层精进。",
            (8, 5, 1),
            42,
            Some("dalun"),
            "基本内功",
        ),
        art(
            "xuantian",
            "玄天无极功",
            "内功",
            "宫门秘传，刚柔并济。",
            (5, 5, 3),
            38,
            Some("court"),
            "基本内功",
        ),
        art(
            "bahuang",
            "八荒六合唯我独尊功",
            "内功",
            "返老还童，威镇群山。",
            (7, 6, 4),
            48,
            Some("lingjiu"),
            "基本内功",
        ),
        art(
            "hamagong",
            "蛤蟆功",
            "掌法",
            "蓄劲如弓，骤发如雷。",
            (8, 3, 2),
            40,
            Some("baituo"),
            "基本拳脚",
        ),
        art(
            "xueshan",
            "雪山剑法",
            "剑法",
            "奇寒凌厉，剑走险峰。",
            (5, 3, 4),
            32,
            Some("xueshan"),
            "基本剑法",
        ),
        art(
            "ningxue",
            "凝血神爪",
            "爪法",
            "出手狠准，制敌要穴。",
            (6, 2, 4),
            36,
            Some("tiandihui"),
            "基本拳脚",
        ),
        art(
            "shenlong",
            "神龙八式",
            "掌法",
            "诡奇狠辣，招招连环。",
            (6, 3, 5),
            39,
            Some("shenlong"),
            "基本拳脚",
        ),
        art(
            "yinyang",
            "阴阳倒乱刃法",
            "刀法",
            "长短双刃，逆势乱敌。",
            (6, 3, 4),
            37,
            Some("jueqing"),
            "基本刀法",
        ),
        art(
            "wudu",
            "五毒神掌",
            "掌法",
            "掌蕴五毒，沾衣伤身。",
            (6, 2, 4),
            35,
            Some("wudu"),
            "基本拳脚",
        ),
        art(
            "songfeng",
            "松风剑法",
            "剑法",
            "轻灵迅捷，如松涛不息。",
            (4, 3, 5),
            28,
            Some("qingcheng"),
            "基本剑法",
        ),
    ];
    let foundations = [
        ("wudang", "武当绵掌"),
        ("huashan", "华山心法"),
        ("mingjiao", "圣火心法"),
        ("quanzhen", "全真心法"),
        ("tianlong", "枯禅心法"),
        ("taohua", "碧波心法"),
        ("shaolin", "少林心法"),
        ("gumu", "古墓心法"),
        ("gaibang", "逍遥游"),
        ("emei", "峨嵋心法"),
        ("riyue", "日月心法"),
        ("xingxiu", "星宿心法"),
        ("murong", "慕容心法"),
        ("dalun", "密宗心法"),
        ("court", "御前拳法"),
        ("lingjiu", "灵鹫心法"),
        ("baituo", "白驼心法"),
        ("xueshan", "雪山心法"),
        ("tiandihui", "百胜刀法"),
        ("shenlong", "神龙心法"),
        ("jueqing", "绝情心法"),
        ("wudu", "五毒心法"),
        ("qingcheng", "鹤唳九霄神功"),
    ];
    arts.extend(foundations.into_iter().map(|(sect, name)| {
        art(
            &format!("{sect}_foundation"),
            name,
            "门派基础",
            "本门弟子入门必修，用以扎稳根基。",
            (2, 3, 2),
            18,
            Some(sect),
            "基本内功",
        )
    }));
    arts
}
